spring:
  jwt:
    secret: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize"
    expiration: 3600000
  datasource:
    url: "jdbc:postgresql://localhost:5432/price-list"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: 'create'
      hbm2ddl:
        auto: 'create'
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "pricelistautomaticmessagebot@gmail.com"
    password: "ppgghqqvwkzbjxna"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  flyway:
    locations:
      - db
    clean-disabled: false
    check-location: false
    baseline-on-migrate: true
destination:
  base: "https://checklistbackend.cfapps.eu10.hana.ondemand.com/"
